import {
  CancelCarnetParamsSchema,
  CancelCarnetParcelParamsSchema,
  CancelCarnetParcelResponseSchema,
  CancelCarnetResponseSchema,
  CancelChargeParamsSchema,
  CancelChargeResponseSchema,
  CancelSubscriptionParamsSchema,
  CancelSubscriptionResponseSchema,
  CardPaymentRetryBodySchema,
  CardPaymentRetryParamsSchema,
  CardPaymentRetryResponseSchema,
  CreateCarnetBodySchema,
  CreateCarnetHistoryBodySchema,
  CreateCarnetHistoryParamsSchema,
  CreateCarnetHistoryResponseSchema,
  CreateCarnetResponseSchema,
  CreateChargeBodySchema,
  CreateChargeCardBodySchema,
  CreateChargeCardResponseSchema,
  CreateChargeHistoryBodySchema,
  CreateChargeHistoryParamsSchema,
  CreateChargeHistoryResponseSchema,
  CreateChargeResponseSchema,
  CreateOneStepChargeBodySchema,
  CreateOneStepChargeResponseSchema,
  CreateOneStepLinkBodySchema,
  CreateOneStepLinkResponseSchema,
  CreateOneStepSubscriptionBodySchema,
  CreateOneStepSubscriptionLinkBodySchema,
  CreateOneStepSubscriptionLinkParamsSchema,
  CreateOneStepSubscriptionLinkResponseSchema,
  CreateOneStepSubscriptionParamsSchema,
  CreateOneStepSubscriptionResponseSchema,
  CreatePlanBodySchema,
  CreatePlanResponseSchema,
  CreateSubscriptionBodySchema,
  CreateSubscriptionHistoryBodySchema,
  CreateSubscriptionHistoryParamsSchema,
  CreateSubscriptionHistoryResponseSchema,
  CreateSubscriptionParamsSchema,
  CreateSubscriptionResponseSchema,
  DefineBalanceSheetBilletBodySchema,
  DefineBalanceSheetBilletParamsSchema,
  DefineBalanceSheetBilletResponseSchema,
  DefineLinkPayMethodBodySchema,
  DefineLinkPayMethodParamsSchema,
  DefineLinkPayMethodResponseSchema,
  DefinePayMethodBodySchema,
  DefinePayMethodParamsSchema,
  DefinePayMethodResponseSchema,
  DefineSubscriptionPayMethodBodySchema,
  DefineSubscriptionPayMethodParamsSchema,
  DefineSubscriptionPayMethodResponseSchema,
  DeletePlanParamsSchema,
  DeletePlanResponseSchema,
  DetailCarnetParamsSchema,
  DetailCarnetResponseSchema,
  DetailChargeParamsSchema,
  DetailChargeResponseSchema,
  DetailSubscriptionParamsSchema,
  DetailSubscriptionResponseSchema,
  GetInstallmentsParamsSchema,
  GetInstallmentsResponseSchema,
  GetNotificationParamsSchema,
  GetNotificationResponseSchema,
  ListChargesParamsSchema,
  ListChargesResponseSchema,
  ListPlansParamsSchema,
  ListPlansResponseSchema,
  RefundCardBodySchema,
  RefundCardParamsSchema,
  RefundCardResponseSchema,
  SendBilletEmailBodySchema,
  SendBilletEmailParamsSchema,
  SendBilletEmailResponseSchema,
  SendCarnetEmailBodySchema,
  SendCarnetEmailParamsSchema,
  SendCarnetEmailResponseSchema,
  SendCarnetParcelEmailBodySchema,
  SendCarnetParcelEmailParamsSchema,
  SendCarnetParcelEmailResponseSchema,
  SendLinkEmailBodySchema,
  SendLinkEmailParamsSchema,
  SendLinkEmailResponseSchema,
  SendSubscriptionLinkEmailBodySchema,
  SendSubscriptionLinkEmailParamsSchema,
  SendSubscriptionLinkEmailResponseSchema,
  SettleCarnetParamsSchema,
  SettleCarnetParcelParamsSchema,
  SettleCarnetParcelResponseSchema,
  SettleCarnetResponseSchema,
  SettleChargeParamsSchema,
  SettleChargeResponseSchema,
  UpdateBilletBodySchema,
  UpdateBilletParamsSchema,
  UpdateBilletResponseSchema,
  UpdateCarnetMetadataBodySchema,
  UpdateCarnetMetadataParamsSchema,
  UpdateCarnetMetadataResponseSchema,
  UpdateCarnetParcelBodySchema,
  UpdateCarnetParcelParamsSchema,
  UpdateCarnetParcelResponseSchema,
  UpdateCarnetParcelsBodySchema,
  UpdateCarnetParcelsParamsSchema,
  UpdateCarnetParcelsResponseSchema,
  UpdateChargeLinkBodySchema,
  UpdateChargeLinkParamsSchema,
  UpdateChargeLinkResponseSchema,
  UpdateChargeMetadataBodySchema,
  UpdateChargeMetadataParamsSchema,
  UpdateChargeMetadataResponseSchema,
  UpdatePlanBodySchema,
  UpdatePlanParamsSchema,
  UpdatePlanResponseSchema,
  UpdateSubscriptionBodySchema,
  UpdateSubscriptionMetadataBodySchema,
  UpdateSubscriptionMetadataParamsSchema,
  UpdateSubscriptionMetadataResponseSchema,
  UpdateSubscriptionParamsSchema,
  UpdateSubscriptionResponseSchema,
} from 'sdk-node-apis-efi';
import { createDomainBuilders } from '../types.js';

const { body, params, optionalParams, paramsBody, paramsOptionalBody } =
  createDomainBuilders('cobrancas');

export const COBRANCAS_DEFINITIONS = [
  paramsOptionalBody({
    method: 'sendSubscriptionLinkEmail',
    httpMethod: 'post',
    route: '/v1/charge/:id/subscription/resend',
    paramsSchema: SendSubscriptionLinkEmailParamsSchema,
    bodySchema: SendSubscriptionLinkEmailBodySchema,
    responseSchema: SendSubscriptionLinkEmailResponseSchema,
  }),
  params({
    method: 'settleCarnet',
    httpMethod: 'put',
    route: '/v1/carnet/:id/settle',
    paramsSchema: SettleCarnetParamsSchema,
    responseSchema: SettleCarnetResponseSchema,
  }),
  paramsOptionalBody({
    method: 'sendLinkEmail',
    httpMethod: 'post',
    route: '/v1/charge/:id/link/resend',
    paramsSchema: SendLinkEmailParamsSchema,
    bodySchema: SendLinkEmailBodySchema,
    responseSchema: SendLinkEmailResponseSchema,
  }),
  body({
    method: 'createOneStepLink',
    httpMethod: 'post',
    route: '/v1/charge/one-step/link',
    bodySchema: CreateOneStepLinkBodySchema,
    responseSchema: CreateOneStepLinkResponseSchema,
  }),
  body({
    method: 'createCharge',
    httpMethod: 'post',
    route: '/v1/charge',
    bodySchema: CreateChargeBodySchema,
    responseSchema: CreateChargeResponseSchema,
  }),
  params({
    method: 'detailCharge',
    httpMethod: 'get',
    route: '/v1/charge/:id',
    paramsSchema: DetailChargeParamsSchema,
    responseSchema: DetailChargeResponseSchema,
  }),
  paramsBody({
    method: 'updateChargeMetadata',
    httpMethod: 'put',
    route: '/v1/charge/:id/metadata',
    paramsSchema: UpdateChargeMetadataParamsSchema,
    bodySchema: UpdateChargeMetadataBodySchema,
    responseSchema: UpdateChargeMetadataResponseSchema,
  }),
  paramsBody({
    method: 'updateBillet',
    httpMethod: 'put',
    route: '/v1/charge/:id/billet',
    paramsSchema: UpdateBilletParamsSchema,
    bodySchema: UpdateBilletBodySchema,
    responseSchema: UpdateBilletResponseSchema,
  }),
  paramsBody({
    method: 'definePayMethod',
    httpMethod: 'post',
    route: '/v1/charge/:id/pay',
    paramsSchema: DefinePayMethodParamsSchema,
    bodySchema: DefinePayMethodBodySchema,
    responseSchema: DefinePayMethodResponseSchema,
  }),
  params({
    method: 'cancelCharge',
    httpMethod: 'put',
    route: '/v1/charge/:id/cancel',
    paramsSchema: CancelChargeParamsSchema,
    responseSchema: CancelChargeResponseSchema,
  }),
  body({
    method: 'createCarnet',
    httpMethod: 'post',
    route: '/v1/carnet',
    bodySchema: CreateCarnetBodySchema,
    responseSchema: CreateCarnetResponseSchema,
  }),
  params({
    method: 'detailCarnet',
    httpMethod: 'get',
    route: '/v1/carnet/:id',
    paramsSchema: DetailCarnetParamsSchema,
    responseSchema: DetailCarnetResponseSchema,
  }),
  paramsBody({
    method: 'updateCarnetParcel',
    httpMethod: 'put',
    route: '/v1/carnet/:id/parcel/:parcel',
    paramsSchema: UpdateCarnetParcelParamsSchema,
    bodySchema: UpdateCarnetParcelBodySchema,
    responseSchema: UpdateCarnetParcelResponseSchema,
  }),
  paramsBody({
    method: 'updateCarnetParcels',
    httpMethod: 'put',
    route: '/v1/carnet/:id/parcels',
    paramsSchema: UpdateCarnetParcelsParamsSchema,
    bodySchema: UpdateCarnetParcelsBodySchema,
    responseSchema: UpdateCarnetParcelsResponseSchema,
  }),
  paramsBody({
    method: 'updateCarnetMetadata',
    httpMethod: 'put',
    route: '/v1/carnet/:id/metadata',
    paramsSchema: UpdateCarnetMetadataParamsSchema,
    bodySchema: UpdateCarnetMetadataBodySchema,
    responseSchema: UpdateCarnetMetadataResponseSchema,
  }),
  params({
    method: 'getNotification',
    httpMethod: 'get',
    route: '/v1/notification/:token',
    paramsSchema: GetNotificationParamsSchema,
    responseSchema: GetNotificationResponseSchema,
  }),
  optionalParams({
    method: 'listPlans',
    httpMethod: 'get',
    route: '/v1/plans',
    paramsSchema: ListPlansParamsSchema,
    responseSchema: ListPlansResponseSchema,
  }),
  body({
    method: 'createPlan',
    httpMethod: 'post',
    route: '/v1/plan',
    bodySchema: CreatePlanBodySchema,
    responseSchema: CreatePlanResponseSchema,
  }),
  params({
    method: 'deletePlan',
    httpMethod: 'delete',
    route: '/v1/plan/:id',
    paramsSchema: DeletePlanParamsSchema,
    responseSchema: DeletePlanResponseSchema,
  }),
  paramsBody({
    method: 'createSubscription',
    httpMethod: 'post',
    route: '/v1/plan/:id/subscription',
    paramsSchema: CreateSubscriptionParamsSchema,
    bodySchema: CreateSubscriptionBodySchema,
    responseSchema: CreateSubscriptionResponseSchema,
  }),
  paramsBody({
    method: 'createOneStepSubscription',
    httpMethod: 'post',
    route: '/v1/plan/:id/subscription/one-step',
    paramsSchema: CreateOneStepSubscriptionParamsSchema,
    bodySchema: CreateOneStepSubscriptionBodySchema,
    responseSchema: CreateOneStepSubscriptionResponseSchema,
  }),
  paramsBody({
    method: 'createOneStepSubscriptionLink',
    httpMethod: 'post',
    route: '/v1/plan/:id/subscription/one-step/link',
    paramsSchema: CreateOneStepSubscriptionLinkParamsSchema,
    bodySchema: CreateOneStepSubscriptionLinkBodySchema,
    responseSchema: CreateOneStepSubscriptionLinkResponseSchema,
  }),
  params({
    method: 'detailSubscription',
    httpMethod: 'get',
    route: '/v1/subscription/:id',
    paramsSchema: DetailSubscriptionParamsSchema,
    responseSchema: DetailSubscriptionResponseSchema,
  }),
  paramsBody({
    method: 'defineSubscriptionPayMethod',
    httpMethod: 'post',
    route: '/v1/subscription/:id/pay',
    paramsSchema: DefineSubscriptionPayMethodParamsSchema,
    bodySchema: DefineSubscriptionPayMethodBodySchema,
    responseSchema: DefineSubscriptionPayMethodResponseSchema,
  }),
  params({
    method: 'cancelSubscription',
    httpMethod: 'put',
    route: '/v1/subscription/:id/cancel',
    paramsSchema: CancelSubscriptionParamsSchema,
    responseSchema: CancelSubscriptionResponseSchema,
  }),
  paramsBody({
    method: 'updateSubscriptionMetadata',
    httpMethod: 'put',
    route: '/v1/subscription/:id/metadata',
    paramsSchema: UpdateSubscriptionMetadataParamsSchema,
    bodySchema: UpdateSubscriptionMetadataBodySchema,
    responseSchema: UpdateSubscriptionMetadataResponseSchema,
  }),
  params({
    method: 'getInstallments',
    httpMethod: 'get',
    route: '/v1/installments',
    paramsSchema: GetInstallmentsParamsSchema,
    responseSchema: GetInstallmentsResponseSchema,
  }),
  paramsOptionalBody({
    method: 'sendBilletEmail',
    httpMethod: 'post',
    route: '/v1/charge/:id/billet/resend',
    paramsSchema: SendBilletEmailParamsSchema,
    bodySchema: SendBilletEmailBodySchema,
    responseSchema: SendBilletEmailResponseSchema,
  }),
  paramsBody({
    method: 'createChargeHistory',
    httpMethod: 'post',
    route: '/v1/charge/:id/history',
    paramsSchema: CreateChargeHistoryParamsSchema,
    bodySchema: CreateChargeHistoryBodySchema,
    responseSchema: CreateChargeHistoryResponseSchema,
  }),
  paramsOptionalBody({
    method: 'sendCarnetEmail',
    httpMethod: 'post',
    route: '/v1/carnet/:id/resend',
    paramsSchema: SendCarnetEmailParamsSchema,
    bodySchema: SendCarnetEmailBodySchema,
    responseSchema: SendCarnetEmailResponseSchema,
  }),
  paramsOptionalBody({
    method: 'sendCarnetParcelEmail',
    httpMethod: 'post',
    route: '/v1/carnet/:id/parcel/:parcel/resend',
    paramsSchema: SendCarnetParcelEmailParamsSchema,
    bodySchema: SendCarnetParcelEmailBodySchema,
    responseSchema: SendCarnetParcelEmailResponseSchema,
  }),
  paramsBody({
    method: 'createCarnetHistory',
    httpMethod: 'post',
    route: '/v1/carnet/:id/history',
    paramsSchema: CreateCarnetHistoryParamsSchema,
    bodySchema: CreateCarnetHistoryBodySchema,
    responseSchema: CreateCarnetHistoryResponseSchema,
  }),
  params({
    method: 'cancelCarnet',
    httpMethod: 'put',
    route: '/v1/carnet/:id/cancel',
    paramsSchema: CancelCarnetParamsSchema,
    responseSchema: CancelCarnetResponseSchema,
  }),
  params({
    method: 'cancelCarnetParcel',
    httpMethod: 'put',
    route: '/v1/carnet/:id/parcel/:parcel/cancel',
    paramsSchema: CancelCarnetParcelParamsSchema,
    responseSchema: CancelCarnetParcelResponseSchema,
  }),
  paramsBody({
    method: 'defineLinkPayMethod',
    httpMethod: 'post',
    route: '/v1/charge/:id/link',
    paramsSchema: DefineLinkPayMethodParamsSchema,
    bodySchema: DefineLinkPayMethodBodySchema,
    responseSchema: DefineLinkPayMethodResponseSchema,
  }),
  paramsBody({
    method: 'updateChargeLink',
    httpMethod: 'put',
    route: '/v1/charge/:id/link',
    paramsSchema: UpdateChargeLinkParamsSchema,
    bodySchema: UpdateChargeLinkBodySchema,
    responseSchema: UpdateChargeLinkResponseSchema,
  }),
  paramsBody({
    method: 'updatePlan',
    httpMethod: 'put',
    route: '/v1/plan/:id',
    paramsSchema: UpdatePlanParamsSchema,
    bodySchema: UpdatePlanBodySchema,
    responseSchema: UpdatePlanResponseSchema,
  }),
  paramsBody({
    method: 'updateSubscription',
    httpMethod: 'put',
    route: '/v1/subscription/:id',
    paramsSchema: UpdateSubscriptionParamsSchema,
    bodySchema: UpdateSubscriptionBodySchema,
    responseSchema: UpdateSubscriptionResponseSchema,
  }),
  paramsBody({
    method: 'createSubscriptionHistory',
    httpMethod: 'post',
    route: '/v1/subscription/:id/history',
    paramsSchema: CreateSubscriptionHistoryParamsSchema,
    bodySchema: CreateSubscriptionHistoryBodySchema,
    responseSchema: CreateSubscriptionHistoryResponseSchema,
  }),
  paramsBody({
    method: 'defineBalanceSheetBillet',
    httpMethod: 'post',
    route: '/v1/charge/:id/balance-sheet',
    paramsSchema: DefineBalanceSheetBilletParamsSchema,
    bodySchema: DefineBalanceSheetBilletBodySchema,
    responseSchema: DefineBalanceSheetBilletResponseSchema,
  }),
  params({
    method: 'settleCharge',
    httpMethod: 'put',
    route: '/v1/charge/:id/settle',
    paramsSchema: SettleChargeParamsSchema,
    responseSchema: SettleChargeResponseSchema,
  }),
  params({
    method: 'settleCarnetParcel',
    httpMethod: 'put',
    route: '/v1/carnet/:id/parcel/:parcel/settle',
    paramsSchema: SettleCarnetParcelParamsSchema,
    responseSchema: SettleCarnetParcelResponseSchema,
  }),
  body({
    method: 'createOneStepCharge',
    httpMethod: 'post',
    route: '/v1/charge/one-step',
    bodySchema: CreateOneStepChargeBodySchema,
    responseSchema: CreateOneStepChargeResponseSchema,
  }),
  paramsBody({
    method: 'cardPaymentRetry',
    httpMethod: 'post',
    route: '/v1/charge/:id/retry',
    paramsSchema: CardPaymentRetryParamsSchema,
    bodySchema: CardPaymentRetryBodySchema,
    responseSchema: CardPaymentRetryResponseSchema,
  }),
  paramsBody({
    method: 'refundCard',
    httpMethod: 'post',
    route: '/v1/charge/card/:id/refund',
    paramsSchema: RefundCardParamsSchema,
    bodySchema: RefundCardBodySchema,
    responseSchema: RefundCardResponseSchema,
  }),
  params({
    method: 'listCharges',
    httpMethod: 'get',
    route: '/v1/charges',
    paramsSchema: ListChargesParamsSchema,
    responseSchema: ListChargesResponseSchema,
  }),
  body({
    method: 'createChargeCard',
    httpMethod: 'post',
    route: '/v2/charge/card',
    bodySchema: CreateChargeCardBodySchema,
    responseSchema: CreateChargeCardResponseSchema,
  }),
] as const;
