import {
  OfCancelAutomaticPixPaymentBodySchema,
  OfCancelAutomaticPixPaymentResponseSchema,
  OfCancelRecurrencyPixParamsSchema,
  OfCancelSchedulePixParamsSchema,
  OfCreateAutomaticEnrollmentBodySchema,
  OfCreateAutomaticEnrollmentResponseSchema,
  OfCreateAutomaticPixPaymentBodySchema,
  OfCreateAutomaticPixPaymentResponseSchema,
  OfCreateBiometricEnrollmentBodySchema,
  OfCreateBiometricEnrollmentResponseSchema,
  OfCreateBiometricPixPaymentBodySchema,
  OfDevolutionPixBodySchema,
  OfDevolutionPixParamsSchema,
  OfDevolutionPixResponseSchema,
  OfDevolutionRecurrencyPixBodySchema,
  OfDevolutionRecurrencyPixParamsSchema,
  OfDevolutionRecurrencyPixResponseSchema,
  OfDevolutionSchedulePixBodySchema,
  OfDevolutionSchedulePixParamsSchema,
  OfDevolutionSchedulePixResponseSchema,
  OfListAutomaticEnrollmentParamsSchema,
  OfListAutomaticEnrollmentResponseSchema,
  OfListAutomaticPixPaymentParamsSchema,
  OfListAutomaticPixPaymentResponseSchema,
  OfListBiometricEnrollmentParamsSchema,
  OfListBiometricEnrollmentResponseSchema,
  OfListBiometricPixPaymentParamsSchema,
  OfListBiometricPixPaymentResponseSchema,
  OfListParticipantsParamsSchema,
  OfListParticipantsResponseSchema,
  OfListPixPaymentParamsSchema,
  OfListPixPaymentResponseSchema,
  OfListRecurrencyPixPaymentParamsSchema,
  OfListRecurrencyPixPaymentResponseSchema,
  OfListSchedulePixPaymentParamsSchema,
  OfListSchedulePixPaymentResponseSchema,
  OfReplaceRecurrencyPixParcelBodySchema,
  OfReplaceRecurrencyPixParcelParamsSchema,
  OfRevokeBiometricEnrollmentBodySchema,
  OfRevokeBiometricEnrollmentResponseSchema,
  OfStartPixPaymentBodySchema,
  OfStartRecurrencyPixPaymentBodySchema,
  OfStartSchedulePixPaymentBodySchema,
  OfUpdateAutomaticEnrollmentBodySchema,
  OfUpdateAutomaticEnrollmentResponseSchema,
  OpenFinanceCancelPaymentResponseSchema,
  OpenFinanceConfigBodySchema,
  OpenFinanceConfigResponseSchema,
  OpenFinanceStartPaymentResponseSchema,
} from 'sdk-node-apis-efi';
import { createDomainBuilders } from '../types.js';

const { noInput, body, params, optionalParams, paramsBody } = createDomainBuilders('open-finance');

export const OPEN_FINANCE_DEFINITIONS = [
  optionalParams({
    method: 'ofListParticipants',
    httpMethod: 'get',
    route: '/participantes/',
    paramsSchema: OfListParticipantsParamsSchema,
    responseSchema: OfListParticipantsResponseSchema,
  }),
  body({
    method: 'ofStartPixPayment',
    httpMethod: 'post',
    route: '/pagamentos/pix',
    bodySchema: OfStartPixPaymentBodySchema,
    responseSchema: OpenFinanceStartPaymentResponseSchema,
  }),
  params({
    method: 'ofListPixPayment',
    httpMethod: 'get',
    route: '/pagamentos/pix',
    paramsSchema: OfListPixPaymentParamsSchema,
    responseSchema: OfListPixPaymentResponseSchema,
  }),
  body({
    method: 'ofConfigUpdate',
    httpMethod: 'put',
    route: '/config',
    bodySchema: OpenFinanceConfigBodySchema,
    responseSchema: OpenFinanceConfigResponseSchema,
  }),
  noInput({
    method: 'ofConfigDetail',
    httpMethod: 'get',
    route: '/config',
    responseSchema: OpenFinanceConfigResponseSchema,
  }),
  paramsBody({
    method: 'ofDevolutionPix',
    httpMethod: 'post',
    route: '/pagamentos/pix/:identificadorPagamento/devolver',
    paramsSchema: OfDevolutionPixParamsSchema,
    bodySchema: OfDevolutionPixBodySchema,
    responseSchema: OfDevolutionPixResponseSchema,
  }),
  params({
    method: 'ofCancelSchedulePix',
    httpMethod: 'patch',
    route: '/pagamentos-agendados/pix/:identificadorPagamento/cancelar',
    paramsSchema: OfCancelSchedulePixParamsSchema,
    responseSchema: OpenFinanceCancelPaymentResponseSchema,
  }),
  params({
    method: 'ofListSchedulePixPayment',
    httpMethod: 'get',
    route: '/pagamentos-agendados/pix',
    paramsSchema: OfListSchedulePixPaymentParamsSchema,
    responseSchema: OfListSchedulePixPaymentResponseSchema,
  }),
  body({
    method: 'ofStartSchedulePixPayment',
    httpMethod: 'post',
    route: '/pagamentos-agendados/pix',
    bodySchema: OfStartSchedulePixPaymentBodySchema,
    responseSchema: OpenFinanceStartPaymentResponseSchema,
  }),
  paramsBody({
    method: 'ofDevolutionSchedulePix',
    httpMethod: 'post',
    route: '/pagamentos-agendados/pix/:identificadorPagamento/devolver',
    paramsSchema: OfDevolutionSchedulePixParamsSchema,
    bodySchema: OfDevolutionSchedulePixBodySchema,
    responseSchema: OfDevolutionSchedulePixResponseSchema,
  }),
  body({
    method: 'ofStartRecurrencyPixPayment',
    httpMethod: 'post',
    route: '/pagamentos-recorrentes/pix',
    bodySchema: OfStartRecurrencyPixPaymentBodySchema,
    responseSchema: OpenFinanceStartPaymentResponseSchema,
  }),
  params({
    method: 'ofListRecurrencyPixPayment',
    httpMethod: 'get',
    route: '/pagamentos-recorrentes/pix',
    paramsSchema: OfListRecurrencyPixPaymentParamsSchema,
    responseSchema: OfListRecurrencyPixPaymentResponseSchema,
  }),
  params({
    method: 'ofCancelRecurrencyPix',
    httpMethod: 'patch',
    route: '/pagamentos-recorrentes/pix/:identificadorPagamento/cancelar',
    paramsSchema: OfCancelRecurrencyPixParamsSchema,
    responseSchema: OpenFinanceCancelPaymentResponseSchema,
  }),
  paramsBody({
    method: 'ofDevolutionRecurrencyPix',
    httpMethod: 'post',
    route: '/pagamentos-recorrentes/pix/:identificadorPagamento/devolver',
    paramsSchema: OfDevolutionRecurrencyPixParamsSchema,
    bodySchema: OfDevolutionRecurrencyPixBodySchema,
    responseSchema: OfDevolutionRecurrencyPixResponseSchema,
  }),
  paramsBody({
    method: 'ofReplaceRecurrencyPixParcel',
    httpMethod: 'patch',
    route: '/pagamentos-recorrentes/pix/:identificadorPagamento/substituir/:endToEndId',
    paramsSchema: OfReplaceRecurrencyPixParcelParamsSchema,
    bodySchema: OfReplaceRecurrencyPixParcelBodySchema,
    responseSchema: OpenFinanceStartPaymentResponseSchema,
  }),
  body({
    method: 'ofCreateBiometricEnrollment',
    httpMethod: 'post',
    route: '/pagamentos-biometria/vinculos',
    bodySchema: OfCreateBiometricEnrollmentBodySchema,
    responseSchema: OfCreateBiometricEnrollmentResponseSchema,
  }),
  params({
    method: 'ofListBiometricEnrollment',
    httpMethod: 'get',
    route: '/pagamentos-biometria/vinculos',
    paramsSchema: OfListBiometricEnrollmentParamsSchema,
    responseSchema: OfListBiometricEnrollmentResponseSchema,
  }),
  body({
    method: 'ofCreateBiometricPixPayment',
    httpMethod: 'post',
    route: '/pagamentos-biometria/pix',
    bodySchema: OfCreateBiometricPixPaymentBodySchema,
    responseSchema: OpenFinanceStartPaymentResponseSchema,
  }),
  params({
    method: 'ofListBiometricPixPayment',
    httpMethod: 'get',
    route: '/pagamentos-biometria/pix',
    paramsSchema: OfListBiometricPixPaymentParamsSchema,
    responseSchema: OfListBiometricPixPaymentResponseSchema,
  }),
  body({
    method: 'ofRevokeBiometricEnrollment',
    httpMethod: 'patch',
    route: '/pagamentos-biometria/vinculos',
    bodySchema: OfRevokeBiometricEnrollmentBodySchema,
    responseSchema: OfRevokeBiometricEnrollmentResponseSchema,
  }),
  body({
    method: 'ofCreateAutomaticEnrollment',
    httpMethod: 'post',
    route: '/pagamentos-automaticos/adesao',
    bodySchema: OfCreateAutomaticEnrollmentBodySchema,
    responseSchema: OfCreateAutomaticEnrollmentResponseSchema,
  }),
  params({
    method: 'ofListAutomaticEnrollment',
    httpMethod: 'get',
    route: '/pagamentos-automaticos/adesao',
    paramsSchema: OfListAutomaticEnrollmentParamsSchema,
    responseSchema: OfListAutomaticEnrollmentResponseSchema,
  }),
  body({
    method: 'ofUpdateAutomaticEnrollment',
    httpMethod: 'patch',
    route: '/pagamentos-automaticos/adesao',
    bodySchema: OfUpdateAutomaticEnrollmentBodySchema,
    responseSchema: OfUpdateAutomaticEnrollmentResponseSchema,
  }),
  body({
    method: 'ofCreateAutomaticPixPayment',
    httpMethod: 'post',
    route: '/pagamentos-automaticos/pix',
    bodySchema: OfCreateAutomaticPixPaymentBodySchema,
    responseSchema: OfCreateAutomaticPixPaymentResponseSchema,
  }),
  params({
    method: 'ofListAutomaticPixPayment',
    httpMethod: 'get',
    route: '/pagamentos-automaticos/pix',
    paramsSchema: OfListAutomaticPixPaymentParamsSchema,
    responseSchema: OfListAutomaticPixPaymentResponseSchema,
  }),
  body({
    method: 'ofCancelAutomaticPixPayment',
    httpMethod: 'patch',
    route: '/pagamentos-automaticos/pix',
    bodySchema: OfCancelAutomaticPixPaymentBodySchema,
    responseSchema: OfCancelAutomaticPixPaymentResponseSchema,
  }),
] as const;
