import {
  CreateReportBodySchema,
  CreateReportResponseSchema,
  DetailReportParamsSchema,
  DetailReportResponseSchema,
  GetAccountBalanceParamsSchema,
  GetAccountBalanceResponseSchema,
  ListAccountConfigResponseSchema,
  MedListParamsSchema,
  MedListResponseSchema,
  MedSubmitDefenseBodySchema,
  MedSubmitDefenseParamsSchema,
  PixConfigWebhookAutomaticChargeBodySchema,
  PixConfigWebhookBodySchema,
  PixConfigWebhookParamsSchema,
  PixConfigWebhookRecurrenceAutomaticBodySchema,
  PixConfigWebhookResponseSchema,
  PixCreateAutomaticChargeBodySchema,
  PixCreateAutomaticChargeResponseSchema,
  PixCreateAutomaticChargeTxidBodySchema,
  PixCreateAutomaticChargeTxidParamsSchema,
  PixCreateAutomaticChargeTxidResponseSchema,
  PixCreateChargeBodySchema,
  PixCreateChargeParamsSchema,
  PixCreateChargeResponseSchema,
  PixCreateDueChargeBatchBodySchema,
  PixCreateDueChargeBatchParamsSchema,
  PixCreateDueChargeBatchResponseSchema,
  PixCreateDueChargeBodySchema,
  PixCreateDueChargeParamsSchema,
  PixCreateDueChargeResponseSchema,
  PixCreateEvpResponseSchema,
  PixCreateImmediateChargeBodySchema,
  PixCreateImmediateChargeResponseSchema,
  PixCreateLocationBodySchema,
  PixCreateLocationRecurrenceAutomaticResponseSchema,
  PixCreateLocationResponseSchema,
  PixCreateRecurrenceAutomaticBodySchema,
  PixCreateRecurrenceAutomaticResponseSchema,
  PixCreateRequestRecurrenceAutomaticBodySchema,
  PixCreateRequestRecurrenceAutomaticResponseSchema,
  PixDeleteEvpParamsSchema,
  PixDeleteWebhookParamsSchema,
  PixDetailAutomaticChargeParamsSchema,
  PixDetailAutomaticChargeResponseSchema,
  PixDetailChargeParamsSchema,
  PixDetailChargeResponseSchema,
  PixDetailDevolutionParamsSchema,
  PixDetailDevolutionResponseSchema,
  PixDetailDueChargeBatchParamsSchema,
  PixDetailDueChargeBatchResponseSchema,
  PixDetailDueChargeParamsSchema,
  PixDetailDueChargeResponseSchema,
  PixDetailLocationParamsSchema,
  PixDetailLocationRecurrenceAutomaticParamsSchema,
  PixDetailLocationRecurrenceAutomaticResponseSchema,
  PixDetailLocationResponseSchema,
  PixDetailReceivedParamsSchema,
  PixDetailReceivedResponseSchema,
  PixDetailRecurrenceAutomaticParamsSchema,
  PixDetailRecurrenceAutomaticResponseSchema,
  PixDetailRequestRecurrenceAutomaticParamsSchema,
  PixDetailRequestRecurrenceAutomaticResponseSchema,
  PixDetailWebhookParamsSchema,
  PixDetailWebhookResponseSchema,
  PixDevolutionBodySchema,
  PixDevolutionParamsSchema,
  PixDevolutionResponseSchema,
  PixGenerateQRCodeParamsSchema,
  PixGenerateQRCodeResponseSchema,
  PixGetReceiptParamsSchema,
  PixKeysBucketResponseSchema,
  PixListAutomaticChargeParamsSchema,
  PixListAutomaticChargeResponseSchema,
  PixListChargesParamsSchema,
  PixListChargesResponseSchema,
  PixListDueChargeBatchParamsSchema,
  PixListDueChargeBatchResponseSchema,
  PixListDueChargesParamsSchema,
  PixListDueChargesResponseSchema,
  PixListEvpResponseSchema,
  PixListLocationRecurrenceAutomaticParamsSchema,
  PixListLocationRecurrenceAutomaticResponseSchema,
  PixListReceivedParamsSchema,
  PixListReceivedResponseSchema,
  PixListRecurrenceAutomaticParamsSchema,
  PixListRecurrenceAutomaticResponseSchema,
  PixListWebhookAutomaticChargeResponseSchema,
  PixListWebhookParamsSchema,
  PixListWebhookRecurrenceAutomaticResponseSchema,
  PixListWebhookResponseSchema,
  PixLocationListParamsSchema,
  PixLocationListResponseSchema,
  PixQrCodeBodySchema,
  PixQrCodeDetailBodySchema,
  PixQrCodeDetailResponseSchema,
  PixQrCodePayParamsSchema,
  PixQrCodePayResponseSchema,
  PixResendWebhookBodySchema,
  PixRetryRequestAutomaticParamsSchema,
  PixRetryRequestAutomaticResponseSchema,
  PixSendBodySchema,
  PixSendDetailIdParamsSchema,
  PixSendDetailIdResponseSchema,
  PixSendDetailParamsSchema,
  PixSendDetailResponseSchema,
  PixSendListParamsSchema,
  PixSendListResponseSchema,
  PixSendParamsSchema,
  PixSendResponseSchema,
  PixSendSameOwnershipBodySchema,
  PixSendSameOwnershipParamsSchema,
  PixSendSameOwnershipResponseSchema,
  PixSplitConfigBodySchema,
  PixSplitConfigIdBodySchema,
  PixSplitConfigIdParamsSchema,
  PixSplitConfigIdResponseSchema,
  PixSplitConfigResponseSchema,
  PixSplitDetailChargeParamsSchema,
  PixSplitDetailChargeResponseSchema,
  PixSplitDetailConfigParamsSchema,
  PixSplitDetailConfigResponseSchema,
  PixSplitDetailDueChargeParamsSchema,
  PixSplitDetailDueChargeResponseSchema,
  PixSplitDevolutionBodySchema,
  PixSplitDevolutionParamsSchema,
  PixSplitDevolutionResponseSchema,
  PixSplitLinkChargeParamsSchema,
  PixSplitLinkDueChargeParamsSchema,
  PixSplitUnlinkChargeParamsSchema,
  PixSplitUnlinkDueChargeParamsSchema,
  PixUnlinkLocationRecurrenceAutomaticParamsSchema,
  PixUnlinkLocationRecurrenceAutomaticResponseSchema,
  PixUnlinkTxidLocationParamsSchema,
  PixUnlinkTxidLocationResponseSchema,
  PixUpdateAutomaticChargeBodySchema,
  PixUpdateAutomaticChargeParamsSchema,
  PixUpdateAutomaticChargeResponseSchema,
  PixUpdateChargeBodySchema,
  PixUpdateChargeParamsSchema,
  PixUpdateChargeResponseSchema,
  PixUpdateDueChargeBatchBodySchema,
  PixUpdateDueChargeBatchParamsSchema,
  PixUpdateDueChargeBatchResponseSchema,
  PixUpdateDueChargeBodySchema,
  PixUpdateDueChargeParamsSchema,
  PixUpdateDueChargeResponseSchema,
  PixUpdateRecurrenceAutomaticBodySchema,
  PixUpdateRecurrenceAutomaticParamsSchema,
  PixUpdateRecurrenceAutomaticResponseSchema,
  PixUpdateRequestRecurrenceAutomaticBodySchema,
  PixUpdateRequestRecurrenceAutomaticParamsSchema,
  PixUpdateRequestRecurrenceAutomaticResponseSchema,
  UpdateAccountConfigBodySchema,
} from 'sdk-node-apis-efi';
import type { StaticPixData, StaticPixResponse } from 'sdk-node-apis-efi';
import { z } from 'zod';
import { createDomainBuilders } from '../types.js';

const StaticPixBodySchema: z.ZodType<StaticPixData> = z
  .object({
    chave: z.string(),
    merchantName: z.string(),
    merchantCity: z.string(),
    transactionAmount: z.number().optional(),
    txid: z.string().optional(),
    infoAdicional: z.string().optional(),
    oneTime: z.boolean().optional(),
    merchantCategoryCode: z.string().optional(),
    transactionCurrency: z.number().optional(),
    countryCode: z.string().optional(),
  })
  .strict();

const StaticPixResponseSchema: z.ZodType<StaticPixResponse> = z
  .object({
    qrcode: z.string(),
    imagemQrcode: z.string(),
  })
  .strict();

const { noInput, body, params, optionalParams, paramsBody } = createDomainBuilders('pix');

export const PIX_DEFINITIONS = [
  paramsBody({
    method: 'pixCreateDueCharge',
    httpMethod: 'put',
    route: '/v2/cobv/:txid',
    paramsSchema: PixCreateDueChargeParamsSchema,
    bodySchema: PixCreateDueChargeBodySchema,
    responseSchema: PixCreateDueChargeResponseSchema,
  }),
  paramsBody({
    method: 'pixUpdateDueCharge',
    httpMethod: 'patch',
    route: '/v2/cobv/:txid',
    paramsSchema: PixUpdateDueChargeParamsSchema,
    bodySchema: PixUpdateDueChargeBodySchema,
    responseSchema: PixUpdateDueChargeResponseSchema,
  }),
  params({
    method: 'pixDetailDueCharge',
    httpMethod: 'get',
    route: '/v2/cobv/:txid',
    paramsSchema: PixDetailDueChargeParamsSchema,
    responseSchema: PixDetailDueChargeResponseSchema,
  }),
  params({
    method: 'pixListDueCharges',
    httpMethod: 'get',
    route: '/v2/cobv/',
    paramsSchema: PixListDueChargesParamsSchema,
    responseSchema: PixListDueChargesResponseSchema,
  }),
  body({
    method: 'createReport',
    httpMethod: 'post',
    route: '/v2/gn/relatorios/extrato-conciliacao',
    bodySchema: CreateReportBodySchema,
    responseSchema: CreateReportResponseSchema,
  }),
  params({
    method: 'detailReport',
    httpMethod: 'get',
    route: '/v2/gn/relatorios/:id',
    paramsSchema: DetailReportParamsSchema,
    responseSchema: DetailReportResponseSchema,
  }),
  paramsBody({
    method: 'pixCreateCharge',
    httpMethod: 'put',
    route: '/v2/cob/:txid',
    paramsSchema: PixCreateChargeParamsSchema,
    bodySchema: PixCreateChargeBodySchema,
    responseSchema: PixCreateChargeResponseSchema,
  }),
  paramsBody({
    method: 'pixUpdateCharge',
    httpMethod: 'patch',
    route: '/v2/cob/:txid',
    paramsSchema: PixUpdateChargeParamsSchema,
    bodySchema: PixUpdateChargeBodySchema,
    responseSchema: PixUpdateChargeResponseSchema,
  }),
  body({
    method: 'pixCreateImmediateCharge',
    httpMethod: 'post',
    route: '/v2/cob',
    bodySchema: PixCreateImmediateChargeBodySchema,
    responseSchema: PixCreateImmediateChargeResponseSchema,
  }),
  params({
    method: 'pixDetailCharge',
    httpMethod: 'get',
    route: '/v2/cob/:txid',
    paramsSchema: PixDetailChargeParamsSchema,
    responseSchema: PixDetailChargeResponseSchema,
  }),
  params({
    method: 'pixListCharges',
    httpMethod: 'get',
    route: '/v2/cob',
    paramsSchema: PixListChargesParamsSchema,
    responseSchema: PixListChargesResponseSchema,
  }),
  params({
    method: 'pixDetailReceived',
    httpMethod: 'get',
    route: '/v2/pix/:e2eId',
    paramsSchema: PixDetailReceivedParamsSchema,
    responseSchema: PixDetailReceivedResponseSchema,
  }),
  params({
    method: 'pixReceivedList',
    httpMethod: 'get',
    route: '/v2/pix',
    paramsSchema: PixListReceivedParamsSchema,
    responseSchema: PixListReceivedResponseSchema,
  }),
  paramsBody({
    method: 'pixSend',
    httpMethod: 'put',
    route: '/v3/gn/pix/:idEnvio',
    paramsSchema: PixSendParamsSchema,
    bodySchema: PixSendBodySchema,
    responseSchema: PixSendResponseSchema,
  }),
  params({
    method: 'pixSendDetail',
    httpMethod: 'get',
    route: '/v2/gn/pix/enviados/:e2eId',
    paramsSchema: PixSendDetailParamsSchema,
    responseSchema: PixSendDetailResponseSchema,
  }),
  params({
    method: 'pixSendList',
    httpMethod: 'get',
    route: '/v2/gn/pix/enviados',
    paramsSchema: PixSendListParamsSchema,
    responseSchema: PixSendListResponseSchema,
  }),
  paramsBody({
    method: 'pixDevolution',
    httpMethod: 'put',
    route: '/v2/pix/:e2eId/devolucao/:id',
    paramsSchema: PixDevolutionParamsSchema,
    bodySchema: PixDevolutionBodySchema,
    responseSchema: PixDevolutionResponseSchema,
  }),
  params({
    method: 'pixDetailDevolution',
    httpMethod: 'get',
    route: '/v2/pix/:e2eId/devolucao/:id',
    paramsSchema: PixDetailDevolutionParamsSchema,
    responseSchema: PixDetailDevolutionResponseSchema,
  }),
  paramsBody({
    method: 'pixConfigWebhook',
    httpMethod: 'put',
    route: '/v2/webhook/:chave',
    paramsSchema: PixConfigWebhookParamsSchema,
    bodySchema: PixConfigWebhookBodySchema,
    responseSchema: PixConfigWebhookResponseSchema,
  }),
  params({
    method: 'pixDetailWebhook',
    httpMethod: 'get',
    route: '/v2/webhook/:chave',
    paramsSchema: PixDetailWebhookParamsSchema,
    responseSchema: PixDetailWebhookResponseSchema,
  }),
  optionalParams({
    method: 'pixListWebhook',
    httpMethod: 'get',
    route: '/v2/webhook',
    paramsSchema: PixListWebhookParamsSchema,
    responseSchema: PixListWebhookResponseSchema,
  }),
  params({
    method: 'pixDeleteWebhook',
    httpMethod: 'delete',
    route: '/v2/webhook/:chave',
    paramsSchema: PixDeleteWebhookParamsSchema,
    responseKind: 'void',
  }),
  body({
    method: 'pixCreateLocation',
    httpMethod: 'post',
    route: '/v2/loc',
    bodySchema: PixCreateLocationBodySchema,
    responseSchema: PixCreateLocationResponseSchema,
  }),
  params({
    method: 'pixLocationList',
    httpMethod: 'get',
    route: '/v2/loc',
    paramsSchema: PixLocationListParamsSchema,
    responseSchema: PixLocationListResponseSchema,
  }),
  params({
    method: 'pixDetailLocation',
    httpMethod: 'get',
    route: '/v2/loc/:id',
    paramsSchema: PixDetailLocationParamsSchema,
    responseSchema: PixDetailLocationResponseSchema,
  }),
  params({
    method: 'pixGenerateQRCode',
    httpMethod: 'get',
    route: '/v2/loc/:id/qrcode',
    paramsSchema: PixGenerateQRCodeParamsSchema,
    responseSchema: PixGenerateQRCodeResponseSchema,
    responseKind: 'qr',
  }),
  params({
    method: 'pixUnlinkTxidLocation',
    httpMethod: 'delete',
    route: '/v2/loc/:id/txid',
    paramsSchema: PixUnlinkTxidLocationParamsSchema,
    responseSchema: PixUnlinkTxidLocationResponseSchema,
  }),
  noInput({
    method: 'pixCreateEvp',
    httpMethod: 'post',
    route: '/v2/gn/evp',
    responseSchema: PixCreateEvpResponseSchema,
  }),
  noInput({
    method: 'pixListEvp',
    httpMethod: 'get',
    route: '/v2/gn/evp',
    responseSchema: PixListEvpResponseSchema,
  }),
  params({
    method: 'pixDeleteEvp',
    httpMethod: 'delete',
    route: '/v2/gn/evp/:chave',
    paramsSchema: PixDeleteEvpParamsSchema,
    responseKind: 'void',
  }),
  optionalParams({
    method: 'getAccountBalance',
    httpMethod: 'get',
    route: '/v2/gn/saldo',
    paramsSchema: GetAccountBalanceParamsSchema,
    responseSchema: GetAccountBalanceResponseSchema,
  }),
  body({
    method: 'updateAccountConfig',
    httpMethod: 'put',
    route: '/v2/gn/config',
    bodySchema: UpdateAccountConfigBodySchema,
    responseKind: 'void',
  }),
  noInput({
    method: 'listAccountConfig',
    httpMethod: 'get',
    route: '/v2/gn/config',
    responseSchema: ListAccountConfigResponseSchema,
  }),
  params({
    method: 'pixSplitDetailCharge',
    httpMethod: 'get',
    route: '/v2/gn/split/cob/:txid',
    paramsSchema: PixSplitDetailChargeParamsSchema,
    responseSchema: PixSplitDetailChargeResponseSchema,
  }),
  params({
    method: 'pixSplitLinkCharge',
    httpMethod: 'put',
    route: '/v2/gn/split/cob/:txid/vinculo/:splitConfigId',
    paramsSchema: PixSplitLinkChargeParamsSchema,
    responseKind: 'void',
  }),
  params({
    method: 'pixSplitUnlinkCharge',
    httpMethod: 'delete',
    route: '/v2/gn/split/cob/:txid/vinculo',
    paramsSchema: PixSplitUnlinkChargeParamsSchema,
    responseKind: 'void',
  }),
  params({
    method: 'pixSplitDetailDueCharge',
    httpMethod: 'get',
    route: '/v2/gn/split/cobv/:txid',
    paramsSchema: PixSplitDetailDueChargeParamsSchema,
    responseSchema: PixSplitDetailDueChargeResponseSchema,
  }),
  params({
    method: 'pixSplitLinkDueCharge',
    httpMethod: 'put',
    route: '/v2/gn/split/cobv/:txid/vinculo/:splitConfigId',
    paramsSchema: PixSplitLinkDueChargeParamsSchema,
    responseKind: 'void',
  }),
  params({
    method: 'pixSplitUnlinkDueCharge',
    httpMethod: 'delete',
    route: '/v2/gn/split/cobv/:txid/vinculo',
    paramsSchema: PixSplitUnlinkDueChargeParamsSchema,
    responseKind: 'void',
  }),
  body({
    method: 'pixSplitConfig',
    httpMethod: 'post',
    route: '/v2/gn/split/config',
    bodySchema: PixSplitConfigBodySchema,
    responseSchema: PixSplitConfigResponseSchema,
  }),
  paramsBody({
    method: 'pixSplitConfigId',
    httpMethod: 'put',
    route: '/v2/gn/split/config/:id',
    paramsSchema: PixSplitConfigIdParamsSchema,
    bodySchema: PixSplitConfigIdBodySchema,
    responseSchema: PixSplitConfigIdResponseSchema,
  }),
  params({
    method: 'pixSplitDetailConfig',
    httpMethod: 'get',
    route: '/v2/gn/split/config/:id',
    paramsSchema: PixSplitDetailConfigParamsSchema,
    responseSchema: PixSplitDetailConfigResponseSchema,
  }),
  params({
    method: 'pixSendDetailId',
    httpMethod: 'get',
    route: '/v2/gn/pix/enviados/id-envio/:idEnvio',
    paramsSchema: PixSendDetailIdParamsSchema,
    responseSchema: PixSendDetailIdResponseSchema,
  }),
  paramsBody({
    method: 'pixCreateDueChargeBatch',
    httpMethod: 'put',
    route: '/v2/lotecobv/:id',
    paramsSchema: PixCreateDueChargeBatchParamsSchema,
    bodySchema: PixCreateDueChargeBatchBodySchema,
    responseSchema: PixCreateDueChargeBatchResponseSchema,
    responseKind: 'void',
  }),
  paramsBody({
    method: 'pixUpdateDueChargeBatch',
    httpMethod: 'patch',
    route: '/v2/lotecobv/:id',
    paramsSchema: PixUpdateDueChargeBatchParamsSchema,
    bodySchema: PixUpdateDueChargeBatchBodySchema,
    responseSchema: PixUpdateDueChargeBatchResponseSchema,
    responseKind: 'void',
  }),
  params({
    method: 'pixDetailDueChargeBatch',
    httpMethod: 'get',
    route: '/v2/lotecobv/:id',
    paramsSchema: PixDetailDueChargeBatchParamsSchema,
    responseSchema: PixDetailDueChargeBatchResponseSchema,
  }),
  params({
    method: 'pixListDueChargeBatch',
    httpMethod: 'get',
    route: '/v2/lotecobv',
    paramsSchema: PixListDueChargeBatchParamsSchema,
    responseSchema: PixListDueChargeBatchResponseSchema,
  }),
  paramsBody({
    method: 'medDefense',
    httpMethod: 'post',
    route: '/v2/gn/infracoes/:idInfracao/defesa',
    paramsSchema: MedSubmitDefenseParamsSchema,
    bodySchema: MedSubmitDefenseBodySchema,
    responseKind: 'void',
  }),
  optionalParams({
    method: 'medList',
    httpMethod: 'get',
    route: '/v2/gn/infracoes',
    paramsSchema: MedListParamsSchema,
    responseSchema: MedListResponseSchema,
  }),
  paramsBody({
    method: 'pixQrCodePay',
    httpMethod: 'put',
    route: '/v2/gn/pix/:idEnvio/qrcode',
    paramsSchema: PixQrCodePayParamsSchema,
    bodySchema: PixQrCodeBodySchema,
    responseSchema: PixQrCodePayResponseSchema,
  }),
  body({
    method: 'pixResendWebhook',
    httpMethod: 'post',
    route: '/v2/gn/webhook/reenviar',
    bodySchema: PixResendWebhookBodySchema,
    responseKind: 'void',
  }),
  params({
    method: 'pixGetReceipt',
    httpMethod: 'get',
    route: '/v2/gn/pix/comprovantes',
    paramsSchema: PixGetReceiptParamsSchema,
    responseKind: 'pdf',
  }),
  paramsBody({
    method: 'pixSendSameOwnership',
    httpMethod: 'put',
    route: '/v2/gn/pix/:idEnvio/mesma-titularidade',
    paramsSchema: PixSendSameOwnershipParamsSchema,
    bodySchema: PixSendSameOwnershipBodySchema,
    responseSchema: PixSendSameOwnershipResponseSchema,
  }),
  noInput({
    method: 'pixKeysBucket',
    httpMethod: 'get',
    route: '/v2/gn/chaves/balde',
    responseSchema: PixKeysBucketResponseSchema,
  }),
  params({
    method: 'pixDetailRecurrenceAutomatic',
    httpMethod: 'get',
    route: '/v2/rec/:idRec',
    paramsSchema: PixDetailRecurrenceAutomaticParamsSchema,
    responseSchema: PixDetailRecurrenceAutomaticResponseSchema,
  }),
  paramsBody({
    method: 'pixUpdateRecurrenceAutomatic',
    httpMethod: 'patch',
    route: '/v2/rec/:idRec',
    paramsSchema: PixUpdateRecurrenceAutomaticParamsSchema,
    bodySchema: PixUpdateRecurrenceAutomaticBodySchema,
    responseSchema: PixUpdateRecurrenceAutomaticResponseSchema,
  }),
  params({
    method: 'pixListRecurrenceAutomatic',
    httpMethod: 'get',
    route: '/v2/rec',
    paramsSchema: PixListRecurrenceAutomaticParamsSchema,
    responseSchema: PixListRecurrenceAutomaticResponseSchema,
  }),
  body({
    method: 'pixCreateRecurrenceAutomatic',
    httpMethod: 'post',
    route: '/v2/rec',
    bodySchema: PixCreateRecurrenceAutomaticBodySchema,
    responseSchema: PixCreateRecurrenceAutomaticResponseSchema,
  }),
  body({
    method: 'pixCreateRequestRecurrenceAutomatic',
    httpMethod: 'post',
    route: '/v2/solicrec',
    bodySchema: PixCreateRequestRecurrenceAutomaticBodySchema,
    responseSchema: PixCreateRequestRecurrenceAutomaticResponseSchema,
  }),
  params({
    method: 'pixDetailRequestRecurrenceAutomatic',
    httpMethod: 'get',
    route: '/v2/solicrec/:idSolicRec',
    paramsSchema: PixDetailRequestRecurrenceAutomaticParamsSchema,
    responseSchema: PixDetailRequestRecurrenceAutomaticResponseSchema,
  }),
  paramsBody({
    method: 'pixUpdateRequestRecurrenceAutomatic',
    httpMethod: 'patch',
    route: '/v2/solicrec/:idSolicRec',
    paramsSchema: PixUpdateRequestRecurrenceAutomaticParamsSchema,
    bodySchema: PixUpdateRequestRecurrenceAutomaticBodySchema,
    responseSchema: PixUpdateRequestRecurrenceAutomaticResponseSchema,
  }),
  paramsBody({
    method: 'pixCreateAutomaticChargeTxid',
    httpMethod: 'put',
    route: '/v2/cobr/:txid',
    paramsSchema: PixCreateAutomaticChargeTxidParamsSchema,
    bodySchema: PixCreateAutomaticChargeTxidBodySchema,
    responseSchema: PixCreateAutomaticChargeTxidResponseSchema,
  }),
  paramsBody({
    method: 'pixUpdateAutomaticCharge',
    httpMethod: 'patch',
    route: '/v2/cobr/:txid',
    paramsSchema: PixUpdateAutomaticChargeParamsSchema,
    bodySchema: PixUpdateAutomaticChargeBodySchema,
    responseSchema: PixUpdateAutomaticChargeResponseSchema,
  }),
  params({
    method: 'pixDetailAutomaticCharge',
    httpMethod: 'get',
    route: '/v2/cobr/:txid',
    paramsSchema: PixDetailAutomaticChargeParamsSchema,
    responseSchema: PixDetailAutomaticChargeResponseSchema,
  }),
  body({
    method: 'pixCreateAutomaticCharge',
    httpMethod: 'post',
    route: '/v2/cobr',
    bodySchema: PixCreateAutomaticChargeBodySchema,
    responseSchema: PixCreateAutomaticChargeResponseSchema,
  }),
  params({
    method: 'pixListAutomaticCharge',
    httpMethod: 'get',
    route: '/v2/cobr',
    paramsSchema: PixListAutomaticChargeParamsSchema,
    responseSchema: PixListAutomaticChargeResponseSchema,
  }),
  params({
    method: 'pixRetryRequestAutomatic',
    httpMethod: 'post',
    route: '/v2/cobr/:txid/retentativa/:data',
    paramsSchema: PixRetryRequestAutomaticParamsSchema,
    responseSchema: PixRetryRequestAutomaticResponseSchema,
  }),
  noInput({
    method: 'pixCreateLocationRecurrenceAutomatic',
    httpMethod: 'post',
    route: '/v2/locrec',
    responseSchema: PixCreateLocationRecurrenceAutomaticResponseSchema,
  }),
  params({
    method: 'pixListLocationRecurrenceAutomatic',
    httpMethod: 'get',
    route: '/v2/locrec',
    paramsSchema: PixListLocationRecurrenceAutomaticParamsSchema,
    responseSchema: PixListLocationRecurrenceAutomaticResponseSchema,
  }),
  params({
    method: 'pixDetailLocationRecurrenceAutomatic',
    httpMethod: 'get',
    route: '/v2/locrec/:id',
    paramsSchema: PixDetailLocationRecurrenceAutomaticParamsSchema,
    responseSchema: PixDetailLocationRecurrenceAutomaticResponseSchema,
  }),
  params({
    method: 'pixUnlinkLocationRecurrenceAutomatic',
    httpMethod: 'delete',
    route: '/v2/locrec/:id/idRec',
    paramsSchema: PixUnlinkLocationRecurrenceAutomaticParamsSchema,
    responseSchema: PixUnlinkLocationRecurrenceAutomaticResponseSchema,
  }),
  body({
    method: 'pixConfigWebhookRecurrenceAutomatic',
    httpMethod: 'put',
    route: '/v2/webhookrec',
    bodySchema: PixConfigWebhookRecurrenceAutomaticBodySchema,
    responseKind: 'void',
  }),
  noInput({
    method: 'pixListWebhookRecurrenceAutomatic',
    httpMethod: 'get',
    route: '/v2/webhookrec',
    responseSchema: PixListWebhookRecurrenceAutomaticResponseSchema,
  }),
  noInput({
    method: 'pixDeleteWebhookRecurrenceAutomatic',
    httpMethod: 'delete',
    route: '/v2/webhookrec',
    responseKind: 'void',
  }),
  body({
    method: 'pixConfigWebhookAutomaticCharge',
    httpMethod: 'put',
    route: '/v2/webhookcobr',
    bodySchema: PixConfigWebhookAutomaticChargeBodySchema,
    responseKind: 'void',
  }),
  noInput({
    method: 'pixListWebhookAutomaticCharge',
    httpMethod: 'get',
    route: '/v2/webhookcobr',
    responseSchema: PixListWebhookAutomaticChargeResponseSchema,
  }),
  noInput({
    method: 'pixDeleteWebhookAutomaticCharge',
    httpMethod: 'delete',
    route: '/v2/webhookcobr',
    responseKind: 'void',
  }),
  paramsBody({
    method: 'pixSplitDevolution',
    httpMethod: 'put',
    route: '/v2/gn/split/pix/:e2eid/devolucao/:id',
    paramsSchema: PixSplitDevolutionParamsSchema,
    bodySchema: PixSplitDevolutionBodySchema,
    responseSchema: PixSplitDevolutionResponseSchema,
  }),
  body({
    method: 'pixQrCodeDetail',
    httpMethod: 'local',
    route: 'local:pix-qrcode-detail',
    bodySchema: PixQrCodeDetailBodySchema,
    responseSchema: PixQrCodeDetailResponseSchema,
  }),
  body({
    method: 'pixGenerateStaticQRCode',
    httpMethod: 'local',
    route: 'local:pix-qrcode-static',
    bodySchema: StaticPixBodySchema,
    responseSchema: StaticPixResponseSchema,
    responseKind: 'qr',
  }),
] as const;
